#---- Main config file ----
"main_config_file": "config/core.yaml"      # Path to main config file relative to Snakefile
#--------------------------

"final_fcs_db": "fcs_gx" # this database will be used for the filtration of the contigs if skip_fcs is False

"tool_containers": []

"stage_coretools":     #TODO: add bionano
    "filtering":
        "hifi": "cutadapt"
        "illumina": "cutadapt"
    "draft_qc":
        "default":
            - "assembly_qc"

"coretool_option_sets":
    "assembly_qc":
        - "default"

"other_tool_option_sets":
    "cutadapt":                 "default"   # Allowed: default
    "porechop_abi":             "default"   # Allowed: default
    "chopper":                  "default"   # Allowed: default
    "fastqc":                   "default"   # Allowed: default
    "mosdepth":                 "default"   # Allowed: default
    "jellyfish":                "default"   # Allowed: default
    "meryl":                    "default"   # Allowed: default
    "smudgeplot":               "default"   # Allowed: default
    "telo_finder":              "default"   # Allowed: default
    "quast":                    "default"   # Allowed: default
    "minimap2":                 "default"   # Allowed: default
    #"curation":                 "default"   # Allowed: default
    "two_read_bam_combiner":    "default"   # Allowed: default
    "pretextmap":               "default"   # Allowed: default
    "pretextsnapshot":          "default"   # Allowed: default
    "gcp":                      "default"   # Allowed: default
    "kat":                      "default"   # Allowed: default
    "juicer_tools_qc":          "default"   # Allowed: default
    "juicer_tools_pre":         "default"   # Allowed: default
    "mapping_pipeline":         "bwa_only"  # Allowed: arima, bwa_only, juicer, pairtools
    "trf":                      "default"
    "wga":                      "default"
    "select_long_scaffolds":    "default"
    "deepvariant":              "default"   # Allowed: default
    "pairtools_parse":          "default"   # Allowed: default
    "samtools_stats":           "default"   # Allowed: default

"tool_manually_adjusted_features": []

"ploidy": 2
"bwa_tool": "bwa-mem2" # Allowed: bwa, bwa-mem2. ARIMA pipeline always uses bwa as bwa-mem2 breaks read order( i.e. read order in bam file is different from read order in fastq file). DO NOT use bwa-mem2 in arima mapping pipeline
"genome_prefix": "genome"
"busco_lineage_list":
    - "mammalia_odb10" #
#Often used BUSCO lineages: mammalia_odb10, vertebrata_odb10, laurasiatheria_odb10, carnivora_odb10,
#                           actinopterygii_odb10, saccharomycetes_odb10, sauropsida_odb10, aves_odb10

"species_name": "species species"
"tax_id": null # necessary for contamination scan via FCS

"database_set": []

"filtered_data":
    - "hifi"
    - "illumina"
    - "nanopore"

"final_kmer_counter": "meryl" # pipeline allows usage of different kmer counter tools, but only one genomesize assessment could be used
"final_kmer_length": 21 # pipeline allows usage of different kmer length, but only one genomesize assessment could be used

"final_kmer_datatype": "illumina"
"assembly_kmer_length":
    - 31 # kmer length to be used for phasing hic reads using assembled and purge_dupsed contigs

"data_types": "draft,illumina"

"mode": "polish"                # Allowed: "preprocessing", "qc", "assembly"
"preprocessing_mode": "default"   # Allowed: "default"
"qc_mode": "default"              # Allowed: "default"
"polish_mode": "pilon"           # Allowed: "default", "full", "purge_dups", "contig"; custom modes could be set in config file

"custom_preprocessing_stages": []
"custom_qc_stages": []
"custom_assembly_stages": []

"skip_stages": {}

#------------ Options specific for cluster ------------
# This option have no effect if pipeline runs on local machine
"queue":
    "cpu": "cpuqueue"
    "gpu": "gpuqueue" # set to null if your cluster doesn't have gpuqueue. Gpuqueue is used only for deepvariant yet
"tool_queue":
    "deepvariant": "gpu"  # Allowed: "gpu", "cpu". GPU queue will be used if it is set here AND if "queue": "gpu" is set , and if GPU imae of deepvariant is available
"nodes":
    "blacklist": []
    "whitelist": []
"rule_nodes":
    "deepvariant":
        "blacklist":
            - "mjolnircomp05fl"
            - "mjolnircomp06fl"
        "whitelist": []
#------------------------------------------------------

"parameter_set": "default" # Choice of genome-size based set of parameters
"use_existing_envs": False # works only if --use-conda flag was set in snakemake command