#---- Main config file ----
"main_config_file": "config/core.yaml"      # Path to main config file relative to Snakefile
#--------------------------
"allowed_databases":
    "kraken2":
        "nt":
            "path":         "/projects/mjolnir1/data/databases/kraken2/nt/20230502/" # add path to nt database
            "memory_mb":    600000
            "threads":      30
            "time":         "03:00:00"
            "in_memory":    True
    "fcs":
        "fcs_gx":
            "path":         "/projects/mjolnir1/people/xsg178/db/fcs/gxdb/" # add path to fcs_gx database
            "image_path":   "/projects/mjolnir1/people/xsg178/soft/FCS-GX/fcs-gx.sif"
            "memory_mb":    512000 # Entire database must be in memory, it requires at least 490 Gbp
            "threads":      30
            "time":         "06:00:00"
            "in_memory":    True
    "fcs_adaptor":
        "adaptor":
            "path":         null # database is embedded in singularity image
            "image_path":   "/projects/mjolnir1/people/xsg178/soft/fcsadaptor/fcs-adaptor.sif"
            "memory_mb":    20000 #
            "threads":      1
            "time":         "01:00:00"
            "in_memory":    True
            "taxonomy":     "eukaryota"
"final_fcs_db": "fcs_gx" # this database will be used for the filtration of the contigs if skip_fcs is False

"tool_containers": []

"stage_coretools":     #TODO: add bionano
    "filtering":
        "hifi": "cutadapt"
        "illumina": "cutadapt"
    "draft_qc":
        "default":
            - "assembly_qc"
    "phase_reads":
        "default":
            - "phase_reads"

"coretool_option_sets":
    "assembly_qc":
        - "default"
    "phase_reads":
        - "phase"
        - "unphase"

"other_tool_option_sets":
    "cutadapt":                 "default"   # Allowed: default
    "porechop_abi":             "default"   # Allowed: default
    "chopper":                  "default"   # Allowed: default
    "fastqc":                   "default"   # Allowed: default
    "mosdepth":                 "default"   # Allowed: default
    "meryl":                    "default"   # Allowed: default
    "quast":                    "default"   # Allowed: default
    "minimap2":                 "default"   # Allowed: default
    #"curation":                 "default"   # Allowed: default
    "mapping_pipeline":         "bwa_only"  # Allowed: arima, bwa_only, juicer, pairtools
    "trf":                      "default"
    "wga":                      "default"
    "select_long_scaffolds":    "default"
    "samtools_stats":           "default"   # Allowed: default

"tool_manually_adjusted_features": []

"ploidy": 2
"bwa_tool": "bwa-mem2" # Allowed: bwa, bwa-mem2. ARIMA pipeline always uses bwa as bwa-mem2 breaks read order( i.e. read order in bam file is different from read order in fastq file). DO NOT use bwa-mem2 in arima mapping pipeline
"genome_prefix": "SledDog1"
"busco_lineage_list":
    - "mammalia_odb10" #
#Often used BUSCO lineages: mammalia_odb10, vertebrata_odb10, laurasiatheria_odb10, carnivora_odb10,
#                           actinopterygii_odb10, saccharomycetes_odb10, sauropsida_odb10, aves_odb10

"species_name": "Sled dog"
"tax_id": null # necessary for contamination scan via FCS

"database_set":
    "kraken2":
        - "nt"                      # configure corresonding entry in "allowed_databases"
    "fcs_adaptor":
        - "adaptor"
    "fcs":
        - "fcs_gx"

"filtered_data":
    - "hifi"
    - "illumina"
    - "nanopore"

"kmer_length": 21
"final_kmer_datatype": "illumina"
"assembly_kmer_length":
    - 31 # kmer length to be used for phasing hic reads using assembled and purge_dupsed contigs

"data_types": "illumina"
"starting_point": "draft"

"mode": "polish"                # Allowed: "preprocessing", "qc", "assembly"
"preprocessing_mode": "default"   # Allowed: "default"
"qc_mode": "default"              # Allowed: "default"
"polish_mode": "phase"           # Allowed: "default"

"custom_preprocessing_stages": []
"custom_qc_stages": []
"custom_assembly_stages": []

"skip_stage_dict": #[]
    #- "read_qc"
    #- "filter_reads"
    #- "nanoqc"
    #- "nanoplot"
    #- "kraken"
    - "busco"


#------------ Options specific for cluster ------------
# This option have no effect if pipeline runs on local machine
"queue":
    "cpu": "cpuqueue"
    "gpu": "gpuqueue" # set to null if your cluster doesn't have gpuqueue. Gpuqueue is used only for deepvariant yet
"tool_queue":
    "deepvariant": "gpu"  # Allowed: "gpu", "cpu". GPU queue will be used if it is set here AND if "queue": "gpu" is set , and if GPU imae of deepvariant is available
"nodes":
    "blacklist": []
    "whitelist": []
"rule_nodes":
    "deepvariant":
        "blacklist":
            - "mjolnircomp05fl"
            - "mjolnircomp06fl"
        "whitelist": []
#------------------------------------------------------

"parameter_set": "big" # Choice of genome-size based set of parameters
"use_existing_envs": False # works only if --use-conda flag was set in snakemake command